tasks:
  - command: |
      mkdir -p /workspace/bin
      sudo ln -s "${GITPOD_REPO_ROOT}/gpm.sh" /workspace/bin/gpm

      gpm install pre-commit

      pre-commit install --install-hooks

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - timonwong.shellcheck
