tasks:
  - command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install

      sudo ln -s "${GITPOD_REPO_ROOT}/gpm.sh" /usr/local/bin/gpm

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - timonwong.shellcheck
