name: Packages
on:
  - push
jobs:
  list_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List packages
        id: list
        run: |
          touch /tmp/output.yaml
          for pkg in $(ls packages/*.sh); do
            no_dir="${pkg/packages\//}"
            no_ext="${no_dir/\.sh/}"
            echo "- ${no_ext}" >> /tmp/output.yaml
          done

          echo "matrix={\"package\":$(cat /tmp/output.yaml | yq -o json -I 0)}" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs:
      - list_packages
    strategy:
      matrix: ${{ fromJSON(needs.list_packages.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "${{ matrix.package }}: Test installation"
        run: |
          docker run \
            --rm \
            --workdir=/workspace/gpm \
            -v "${GITHUB_WORKSPACE}/packages:/workspace/gpm/packages" \
            gitpod/workspace-base \
            bash -c \
              "source \"./packages/${{ matrix.package }}.sh\" && gpm_${{ matrix.package }}_install"
